In [12]:
import numpy as np

In [13]:
a = np.arange(0,20,2)

In [14]:
b = np.arange(15).reshape(3,5)

In [15]:
a.ndim

1

In [16]:
b.ndim

2

In [17]:
a.shape

(10,)

In [18]:
b.shape

(3, 5)

In [19]:
a.size

10

In [20]:
b.size

15

In [21]:
b[2,2]

12

In [22]:
a[0:5]

array([0, 2, 4, 6, 8])

In [23]:
a[:6]

array([ 0,  2,  4,  6,  8, 10])

In [24]:
b[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [25]:
b[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [26]:
b[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [27]:
b[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [28]:
b[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
b[0,:]

array([0, 1, 2, 3, 4])

In [31]:
b[:,0]

array([ 0,  5, 10])

In [33]:
subb = b[:2,:3]

In [35]:
subb

array([[0, 1, 2],
       [5, 6, 7]])

In [39]:
subb[1,1] = 999
subb

array([[  0,   1,   2],
       [  5, 999,   7]])

In [40]:
b

array([[  0,   1,   2,   3,   4],
       [  5, 999,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [41]:
##修改子矩阵会影响原矩阵

In [44]:
subb = b[:2,:3].copy()
subb
subb[1,1]=888

In [45]:
b

array([[  0,   1,   2,   3,   4],
       [  5, 999,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [47]:
subb

array([[  0,   1,   2],
       [  5, 888,   7]])

In [48]:
b

array([[  0,   1,   2,   3,   4],
       [  5, 999,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [49]:
b.reshape(5,-1)

array([[  0,   1,   2],
       [  3,   4,   5],
       [999,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14]])